### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SuperBlueEyeBall** [DarkSnakeGang/GoogleSnakeModsWebsite#1]
Not really an issue but I have a question. How did you manage to download the source files for the google snake fbx page? I have tried various websites, HTTrack, and more. Is it the settings you used for HTTrack? I have no idea. This would be really valuable for me. Thanks in advance.

**Comment by hwatson381** [comment]
@SuperBlueEyeBall I tried HTTrack when setting this up, but couldn't get it to work properly. In the end I decided to go for a semi-manual process. All the various source files are available in inspect element (you might have to look in a few different places, like the sources tab and the network tab). So the fully manual process would be to get everything from there.

What we do instead is we get the html file from the network tab and then we use a tampermonkey script to help get the rest. The tampermonkey script runs on the fbx page and gets all the URLs used in script tags, javascript fetchs and ajax requests. Once we know the URLs that are requested, we then use a nodejs script to download from these URLs.

After that the last step is to identify what each of the downloaded files are for (as they have random names). Then for being able to reproduce the site, you need to modify some of the files as otherwise they will make requests to google.
